services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: gethomepage
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
      HOMEPAGE_ALLOWED_HOSTS: 192.168.0.2:3000
    ports:
      - 3000:3000
    volumes:
      - "$PATH_TO_CONFIG:/app/config"         # Make sure your local config directory exists
      - "$PATH_TO_IMAGES:/app/public/images"
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: always
